spring.application.name=job-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flowforge?options=-c%20TimeZone%3DUTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:flowforge}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:flowforge_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


spring.kafka.consumer.group-id=flowforge-workers
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.flowforge.jobservice.kafka
spring.kafka.consumer.properties.spring.json.value.default.type=com.flowforge.jobservice.kafka.JobEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

server.port=8080